import fs from 'node:fs';
import path from 'node:path';
import { lintPack, loadPack } from './pack.js';
import {
  CLASSIFICATIONS,
  PROFILE_ROLES,
  classificationRank,
} from './spec.js';
import type { Classification, LoadedDocument } from './types.js';

export interface ContextOptions {
  profile?: keyof typeof PROFILE_ROLES;
  clearance?: Classification;
  allowInvalid?: boolean;
  allowDraft?: boolean;
}

export interface ContextResult {
  markdown: string;
  files: string[];
  profile: string;
  clearance: Classification;
}

export function createContext(input: string, options: ContextOptions = {}): ContextResult {
  const profile = options.profile ?? 'all';
  const clearance = options.clearance ?? 'internal';
  const roles = PROFILE_ROLES[profile];
  if (!roles) throw new Error(`Unknown profile ${profile}. Choose: ${Object.keys(PROFILE_ROLES).join(', ')}`);
  if (!CLASSIFICATIONS.includes(clearance)) throw new Error(`Unknown clearance ${clearance}`);

  if (!options.allowInvalid) {
    const report = lintPack(input);
    if (!report.valid) {
      throw new Error(`Context pack has ${report.summary.errors} validation error(s); run companymd lint first`);
    }
  }

  const pack = loadPack(input);
  const selected = pack.documents.filter((document) => roles.includes(document.role));
  const deprecated = selected.filter((document) => document.parsed?.meta.status === 'deprecated');
  if (deprecated.length > 0) {
    throw new Error(`Deprecated context cannot be bundled: ${deprecated.map((document) => path.relative(pack.root, document.path)).join(', ')}`);
  }
  const drafts = selected.filter((document) => document.parsed?.meta.status === 'draft');
  if (drafts.length > 0 && !options.allowDraft) {
    throw new Error(`Draft context requires --allow-draft: ${drafts.map((document) => path.relative(pack.root, document.path)).join(', ')}`);
  }
  const blocked = selected.filter((document) => classificationRank(classificationOf(document, pack.company.meta.classification)) > classificationRank(clearance));
  if (blocked.length > 0) {
    const names = blocked.map((document) => path.relative(pack.root, document.path)).join(', ');
    throw new Error(`Clearance ${clearance} is insufficient for: ${names}`);
  }

  const files = selected.map((document) => path.relative(pack.root, document.path));
  const generatedAt = new Date().toISOString();
  const preamble = [
    '<!-- Generated by Company.md. Do not edit this bundle; edit its source files. -->',
    '# Company context bundle',
    '',
    `- Profile: ${profile}`,
    `- Clearance: ${clearance}`,
    `- Generated: ${generatedAt}`,
    `- Sources: ${files.join(', ')}`,
    '',
    '## Agent contract',
    '',
    '- Use this context only within the scope and classification declared by each source.',
    '- Prefer verified claims over assumptions; never turn an open question into a fact.',
    '- When scoped overlays conflict with a base document, the more specific overlay wins.',
    '- Do not invent pricing, proof, promises, customer facts, or brand rules.',
    '- For visual work, apply DESIGN.md only after the business, customer, offer, and voice constraints.',
  ].join('\n');

  const bodies = selected.map((document) => {
    const relative = path.relative(pack.root, document.path);
    const inherited = document.inherited ? ' (inherited base)' : '';
    return [
      '',
      '---',
      '',
      `# Source: ${relative}${inherited}`,
      '',
      document.content.trim(),
    ].join('\n');
  });

  return {
    markdown: `${preamble}${bodies.join('\n')}\n`,
    files,
    profile,
    clearance,
  };
}

export function writeContext(result: ContextResult, output: string): void {
  fs.writeFileSync(path.resolve(output), result.markdown, 'utf8');
}

function classificationOf(document: LoadedDocument, companyClassification: unknown): Classification {
  if (document.role === 'design') return asClassification(companyClassification) ?? 'internal';
  return asClassification(document.parsed?.meta.classification) ?? 'restricted';
}

function asClassification(value: unknown): Classification | undefined {
  return typeof value === 'string' && CLASSIFICATIONS.includes(value as Classification)
    ? value as Classification
    : undefined;
}
